### ISSUE TITLE
extract core counter classes into counter

### ISSUE THREAD

**Issue by rosenstrauch** [acolono/opencounter_api#16]
As a developer
In order to create a clear boundary between 
- domain layer,
- framework and
- application,
  I believe OpenCounter core classes should be in their own repo (composer package).

Hypothesis:
I believe splitting out counter classes will allow reusing them in other approaches - decoupled from Slim Framework - which could lead to better code. I also believe this would be a useful separation of concerns, resulting in a clear bounded domain context.

Cost to learn:
12hrs R&D

Plan to proceed:
- Extract core counter classes, interfaces and tests to separate components installed via composer.
- Keep Slim specific stuff in slim counter repo
- Try using core in other prototype

What's needed to proceed:
- another non-slim prototype

**Comment by Nebel54** [comment]
Liebe Kunden, Freunde und Spammer,
wir sind bis inkl. 18.9.2016 nicht im Büro und können Ihre Anfragen daher nicht sofort beantworten. Wir werden unsere E-Mails aber in unregelmäßigen Abständen abrufen und beantworten. 

Liebe Grüße
Oliver Köhler
