### ISSUE TITLE
Merge Codenv and slimcounter and using

### ISSUE THREAD

**Issue by rosenstrauch** [acolono/opencounter_api#33]
In order to have the build server use the same docker containers as we use for development and possibly publish a production ready docker image
- [X] incorporate codenv into this repo
- [X] move appspecific code (that isnt codenv) into a directory named "app"
- [X] adjust build job to use containers defined with docker-compose
https://docs.gitlab.com/ce/ci/docker/using_docker_build.html

Related issues and notes

[gitlab-ce: Caching for docker-in-docker builds](https://gitlab.com/gitlab-org/gitlab-ce/issues/17861)
[docker: specify images used as a cache source on build.](https://github.com/docker/docker/pull/26839)

**Comment by rosenstrauch** [comment]
is this a bad idea to couple dev environment and app in a single repo? shouldnt these stay seperated into two repos?

**Comment by Nebel54** [comment]
i would prefer to have it separated for public projects

**Comment by rosenstrauch** [comment]
then we might need a [docker registry](http://docs.gitlab.com/ce/administration/container_registry.html) to pass built docker images between codenv and slimcounter

**Comment by rosenstrauch** [comment]
done
